### ISSUE TITLE
where you get variable $env

### ISSUE THREAD

**Issue by mishin** [oklahomer/p5-Facebook-OpenGraph#10]
in example
my $req = Plack::Request->new($env) 
??

**Comment by oklahomer** [comment]
Maybe [the synopsis on Plack::Request](https://metacpan.org/pod/Plack::Request) help you.
Remember the code fragments on Synopsis part of Facebook::OpenGraph are not supposed to run as-is.
These just give **general** ideas how it can be coded.

**Comment by mishin** [comment]
thanks, close it
