### ISSUE TITLE
Unsupported video-upload (?)

### ISSUE THREAD

**Issue by christophhalbi** [oklahomer/p5-Facebook-OpenGraph#22]
Hi,

I think that the current video-upload process of facebook (https://developers.facebook.com/docs/graph-api/video-uploads) isn't supported yet or I'm to stupid to use it correctly.

For phase 2 (transfer) I use some like:

```
my $res_transfer = $self->facebook->publish('/me/videos', {
            upload_phase      => 'transfer',
            start_offset      => $start_offset,
            upload_session_id => $upload_session_id,
            video_file_chunk  => read_binary($file_chunk),
        });
```

but all I get is a warning from facebook: 'error' => '2:1363030 OAuthException:Service temporarily unavailable.

If there is a problem, I guess it some near https://metacpan.org/release/Facebook-OpenGraph/source/lib/Facebook/OpenGraph.pm#L454 where the request is set-up. Maybe something wrong with form-data?

Cheers
Chris

**Comment by oklahomer** [comment]
Hmm, I remember I checked its behavior with images years ago. I'll need to take a look at this weekend.

**Comment by oklahomer** [comment]
NOTE:
With the current implementation, only [Non-Resumable Uploading](https://developers.facebook.com/docs/graph-api/video-uploads#nonresumable) is supported; Facebook did not support [Resumable Uploading](https://developers.facebook.com/docs/graph-api/video-uploads#resumable) back in that time. According to the Changelog, it looks like this feature was introduced as part of [Graph API v2.8](https://developers.facebook.com/docs/graph-api/changelog/archive#gapi-new-resumable-v2-8).
To support this, at least another criteria to switch and use alternative host -- graph-video.facebook.com -- is required.

**Comment by oklahomer** [comment]
@christophhalbi I added some changes at #27 to support Resumable Uploading.
However, I could not have a chance to try this feature by myself since `publish_actions` permission is already deprecated and `publish_video` did not seem to work with a personal token to post to timeline as stated at https://developers.facebook.com/docs/graph-api/video-uploads#finish
Or I was simply reproducing this issue: https://developers.facebook.com/community/threads/2155365864590592/

So can you take a look at the changes on #27 and give me feedback?

**Comment by christophhalbi** [comment]
Can you give me an example of Non-Resumable Uploading? Seems like it's not working for me either.

**Comment by oklahomer** [comment]
It's not??
I thought you already stepped into the "transfer" phase considering your example code. Didn't you call "start?"

**Comment by christophhalbi** [comment]
Yes but start is the first phase of Resumable Uploading. I've implemented the actual transfer with a plan CURL call.

Then I tried to use Non-Resumable Uploading by doing a request on me/videos with file_url but this doesn't seem to work either.

**Comment by oklahomer** [comment]
So you have called "start" phase of the vide upload API, @christophhalbi . Good. Did you get a valid response that includes "upload_session_id?" If so, I suppose your token has a video upload privilege. You can take look at below test code to see what request parameters look like.
- https://github.com/oklahomer/p5-Facebook-OpenGraph/pull/27/files#diff-1ee08b258ef2a2d5ed35c242b81fdeceR104-R114
- https://github.com/oklahomer/p5-Facebook-OpenGraph/pull/27/files#diff-1ee08b258ef2a2d5ed35c242b81fdeceR168-R180

**Comment by christophhalbi** [comment]
When I use something like

```
my $res = $self->facebook->publish('/me/videos', {
    file_url    => $self->posting_data->video_uri,
    title       => $self->posting_data->link_name,
    description => $self->posting_data->message,
});
```

I get a timeout ^^

**Comment by oklahomer** [comment]
With the current implementation, you can replace `Furl::HTTP` instance with a prolonged timeout setting as described in #23. I hope it helps, @christophhalbi.

**Comment by christophhalbi** [comment]
Thank you very much!

**Comment by oklahomer** [comment]
Thank you for confirming those changes at https://github.com/oklahomer/p5-Facebook-OpenGraph/pull/27#pullrequestreview-286143998.
This is now released as [Facebook::OpenGraph 1.30.0](https://metacpan.org/source/OKLAHOMER/Facebook-OpenGraph-1.30/lib/Facebook/OpenGraph.pm#L453-487).
I hope this latest version of `Facebook::OpenGraph` helps your video implementation.

**Comment by christophhalbi** [comment]
Hi. Another question popped up: Is the setting of captions via captions_file supported?

https://developers.facebook.com/docs/graph-api/reference/video/captions/

**Comment by oklahomer** [comment]
I don't think `captions_file` parameter with /{video-id}/captions endpoint works at this point.
I'd like to keep this thread for video upload, so could you open another issue for that @christophhalbi ?
Then this particular issue can be closed.

**Comment by christophhalbi** [comment]
Of course. Thanks for your support.
