### ISSUE TITLE
Upload of captions_file

### ISSUE THREAD

**Issue by christophhalbi** [oklahomer/p5-Facebook-OpenGraph#30]
Is the setting of captions via captions_file supported?

https://developers.facebook.com/docs/graph-api/reference/video/captions/

I quess should be added here as well?
https://metacpan.org/release/Facebook-OpenGraph/source/lib/Facebook/OpenGraph.pm#L587

**Comment by oklahomer** [comment]
@christophhalbi , sorry for my belated reply.
Now `captions_file` parameter should be supported with #31.
You are more than welcome to review the changes.

**Comment by oklahomer** [comment]
Oops, this issue was closed automatically when I merge/closed #31.
I'll leave a comment when it is published to CPAN.

**Comment by oklahomer** [comment]
@christophhalbi Now a newer version of [1.31](https://metacpan.org/release/OKLAHOMER/Facebook-OpenGraph-1.31) is available with `captions_file` support. Thank you for your cooperation.
